Mobile view
citec-47/portfolio pull request #2
Opened 2023-01-13 19:29 UTC by citec-47

# Mobile view
This project is to illustrate a website on a mobile device with the following sections 📑;
- Recent work
- Projects
- About me
- Skills
<img src="https://media.giphy.com/media/LKA9Ts0dtUyldwhBbS/giphy.gif">

2023-01-13 22:17 UTC, ridwanediallo requested changes
# Changes Required ♻️
## Hi @citec-47 , 
![AlmostThereReachGIF](https://user-images.githubusercontent.com/55918904/191301799-36d07166-0e35-4582-a231-7a2d780f7783.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- All linters checks are ok. ✔


## Required Changes ♻️

- [ ] Please I think you can remove this 👇️ from your readme file
![Screenshot from 2023-01-13 21-15-19](https://user-images.githubusercontent.com/89228743/212421206-6e606d56-877c-4d55-ba49-fa0f9206c39c.png)
In fact, you should personalize your readme file as much as possible. And, for example, the Microverse logo is there as a placeholder for you if you have your own logo to put there; otherwise, you should remove it because this is your project, not a Microverse project. 👌 I believe you understand what I mean. 😄

- [ ] Please fix your readme file's twitter handler, which is not working as a link. Because it will be much easier for the person viewing your portfolio to check out your Twitter account if it is a link. Please correct it. 👇️
![Screenshot from 2023-01-13 21-15-51](https://user-images.githubusercontent.com/89228743/212423929-a6e18083-ad5f-40c8-a61c-f63230c7ebd1.png)

- [ ] The link to your lincense is broken please fix it as well. 👇️
![Screenshot from 2023-01-13 21-16-04](https://user-images.githubusercontent.com/89228743/212423944-26eca42d-b662-4db6-9afd-8668d30bf438.png)

- [ ] Last but not least, we'd like to change the title of your pull request to something more descriptive because from it we can't tell what your pull PR is about.😄

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 22:17 UTC, ridwanediallo commented on index.html
> +    </ul>
- [ ] Please use the same style used in Figma template for your spans: Languages, Frameworks, and Skills. 👍️

### Your design 👇️

![Screenshot from 2023-01-13 22-03-44](https://user-images.githubusercontent.com/89228743/212427748-247e6b60-0d1c-4ab0-b1d8-4388c9e7ccb9.png)

### The original design 👇️
![Screenshot from 2023-01-13 21-56-56](https://user-images.githubusercontent.com/89228743/212427582-c22cf145-2418-459d-b84d-b8024876485b.png)

2023-01-13 22:17 UTC, ridwanediallo commented on style.css
> +}
- [ ] Kindle use this `#1C1A19;` for the background colour of your about section instead of a black one.

2023-01-14 07:55 UTC, Zuhaib042 requested changes
Hi @citec-47, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![close](https://media.giphy.com/media/nYYtQdLqwwlTe3ccKh/giphy.gif)

 ## Highlights
- GitHub flow is used correctly. ✔
- All linters checks are ok. ✔

 ## Required Changes ♻️
- [ ] I can see that some of the sections of README like the `SETUP` and `INSTALL` was there in the previous PR but I don't see them now. Also there are other sections of README that are missing. MIcroverse urge us to not remove any of the section in the readme except the FAQ section. and they urge us to fill all the sections with appropriate information. In case of not complying the PR can be invalidated. kindly add those sections that were there in the previous PR and fill them
- [OPTIONAL] For best practices and to make your README look more professional, you can add all those sections that you remove and fill them.
- [OPTIONAL] All of the images' links in your repo are working fine when I clone the repository. but when I run the `index.html` in a proper browser environment, then all the images' links get broken and don't work. You can fix them by adding a dot at the beginning of the image's `src` link. for example instead of `src="/image/Vector2.png"`, you can write this:- `src="./image/Vector2.png"`
- [OPTIONAL] Your code is not indented properly. you can fix that by installing `prettier` extension in your `vscode`.
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 07:55 UTC, Zuhaib042 commented on README.md
>  This project is [MIT](./LICENSE) licensed.
- [ ] As previous code reviewer mentioned to fix this link because it is broken. The reason of that is you don't have a `LICENSE.md` file in your repo. Kindly add that file to your repo to make this link work and check its working status before submitting for review.

2023-01-14 07:55 UTC, Zuhaib042 commented on README.md
> + 👥 Authors <a href="https://www.linkedin.com/in/ndonyi-maurice-b5b49b22b/>linked</a>
- [ ] This link and line should not be here. it makes your repo look unprofessional. I would suggest removing it.

2023-01-14 07:55 UTC, Zuhaib042 commented on index.html
> +          </div>
- [ ] As the previous code reviewer mentioned, kindly consider removing these two `</div>` from your code as they are extra and unnecessary and a violation of best practices in HTML.

2023-01-14 07:55 UTC, Zuhaib042 commented on index.html
> +      <li class="skillIcons"><h4>Frameworks</h4></li>
- [ ] As the previous code reviewer mentioned the differences between your design and the figma design regarding to skill section. I can still see the irregularity and dissimilarity between `Langugages` and `Frameworks` headings.
they both must be similar in font-weight and font-size as we need to be consistent in our design to make is perfect and good-looking. kindly consider fixing that.
- [ ] And the alignment of these two headings is also off. kindly consider fixing that also.
your design
![qw](https://user-images.githubusercontent.com/96683843/212462138-d434de65-f644-42f8-9548-62a64524a5f4.jpg)
figma design
![qwer](https://user-images.githubusercontent.com/96683843/212462144-c56f7d86-33ad-4557-a4a0-2de4631f34b3.jpg)

2023-01-14 10:53 UTC, AlphaNtihinduka approved these changes
# STATUS: APPROVED :green_circle: :clap: 
## Hi @citec-47    🙋‍♂️, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
![approved-accepted](https://user-images.githubusercontent.com/99394374/212468428-4e899845-d979-455c-83a2-6a191f8688b5.gif)



Congratulations! 🎉 
TO HIGHLIGHT:

- Your project is professional ✅
- Your repo is professional ✅
- Well-structured files ✅
- Professional README.md file 💯

Now you can merge this branch and move on :1st_place_medal: 

## Optional suggestions
- [ ] As stated in the inline comments. Please ensure that all the `<h1>` elements are used in proper way following semantic HTML guidelines.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :four_leaf_clover:

2023-01-14 10:53 UTC, AlphaNtihinduka commented on index.html
> +</h1>
- [ ] Kindly consider use of `<h1>` tag once in a a page. This is because for [Semantic HTML](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwisnebC8Mb8AhX-8bsIHZBQArsQFnoECAsQAw&url=https%3A%2F%2Fdeveloper.mozilla.org%2Fen-US%2Fdocs%2FGlossary%2FSemantics&usg=AOvVaw1B6qsXIooodDa3t1Uxayp1) purposes the ` <h1>` element is a semantic element, which gives the text it wraps around the role( or meaning) of a top level heading on your page. For this case you may consider using `<h2> - <h6>` elements.

2023-01-14 10:53 UTC, AlphaNtihinduka commented on index.html
> +  </h1>
- [ ] Kindly consider use of `<h1>` tag once in a a page. This is because for [Semantic HTML](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwisnebC8Mb8AhX-8bsIHZBQArsQFnoECAsQAw&url=https%3A%2F%2Fdeveloper.mozilla.org%2Fen-US%2Fdocs%2FGlossary%2FSemantics&usg=AOvVaw1B6qsXIooodDa3t1Uxayp1) purposes the ` <h1>` element is a semantic element, which gives the text it wraps around the role( or meaning) of a top level heading on your page. For this case you may consider using `<h2> - <h6>` elements.

2023-01-14 10:53 UTC, AlphaNtihinduka commented on index.html
> +    </h1>
- [ ] Kindly consider use of `<h1>` tag once in a a page. This is because for [Semantic HTML](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwisnebC8Mb8AhX-8bsIHZBQArsQFnoECAsQAw&url=https%3A%2F%2Fdeveloper.mozilla.org%2Fen-US%2Fdocs%2FGlossary%2FSemantics&usg=AOvVaw1B6qsXIooodDa3t1Uxayp1) purposes the ` <h1>` element is a semantic element, which gives the text it wraps around the role( or meaning) of a top level heading on your page. For this case you may consider using `<h2> - <h6>` elements.

2023-01-14 10:59 UTC, merged